language: csharp
#sudo: required
sudo: false
dist: trusty # Ubuntu 14.04
mono: none
dotnet : 2.2.0
addons:
  apt:
    packages:
      - libunwind8

before_install:
 - dotnet restore build.proj

script:
 - dotnet fake build --target dotnettests

branches:
  except:
    - gh-pages
    - release
