language: csharp
dist: trusty # Ubuntu 14.04
mono: none

before_install:
    - wget -q https://packages.microsoft.com/config/ubuntu/14.04/packages-microsoft-prod.deb
    - sudo apt-get install -y dpkg 
    - sudo dpkg -i packages-microsoft-prod.deb
    - sudo apt-get install apt-transport-https
    - sudo apt-get update
    - sudo apt-get install dotnet-sdk-2.2
    - export DOTNET_ROOT=$HOME/dotnet 
    - export PATH=$PATH:$HOME/dotnet
    - dotnet tool install fake-cli -g --version 5.11.1
    - dotnet restore build.proj

#addons:
#  apt:
#    packages:
#      - libunwind8

script:
 - dotnet fake build --target dotnettests

branches:
  except:
    - gh-pages
    - release
